[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
gas_reports = ["*"]
optimizer = true
optimizer_runs = 200

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 125
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4